# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "13.4.2"

package:
  name: "mog"
  version: 0.1.5

source:
  - path: .
  - path: ../LICENSE
  - path: ../test

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - magic run mojo package mog
    - cp mog.mojopkg ${PREFIX}/lib/mojo/mog.mojopkg

requirements:
  run:
    - gojo >= 0.1.9,<0.2
    - max >= 24.5.0,<25
    - weave >= 0.1.1,<0.2
    - mist >= 0.1.5,<0.2

tests:
  - script:
      # commands to run to test the package. If any of the commands
      # returns with an error code, the test is considered failed.
      # if I don't copy everything into a test dir, mojo test runs the tests in the .magic dir and fails :|
      - mkdir -p test
      - mv test_*.mojo test/
      - mv mog.mojopkg test/
      - magic run mojo test test

    files:
      # Extra files to be copied to the test directory from the "work directory"
      source:
        - mog.mojopkg
        - mojoproject.toml
        - test_*.mojo

about:
  homepage: https://github.com/thatstoasty/mog
  license: MIT
  license_file: LICENSE
  summary: Style definitions for nice terminal layouts. Built with TUIs in mind. https://github.com/thatstoasty/mog
  repository: https://github.com/thatstoasty/mog
