# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "13.4.2"

package:
  name: "mist"
  version: 0.1.3.nightly

source:
  - path: .
  - path: ../LICENSE
  - path: ../test

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - magic run mojo package mist
    - cp mist.mojopkg ${PREFIX}/lib/mojo/mist.mojopkg

requirements:
  run:
    - gojo >= 0.1.6.nightly
    - hue >= 0.1.3.nightly
    - max >= 24.6.0.dev2024091205

tests:
  - script:
      # commands to run to test the package. If any of the commands
      # returns with an error code, the test is considered failed.
      # if I don't copy everything into a test dir, mojo test runs the tests in the .magic dir and fails :|
      - mkdir -p test
      - mv test_*.mojo test/
      - mv mist.mojopkg test/
      - magic run mojo test test

    files:
      # Extra files to be copied to the test directory from the "work directory"
      source:
        - mist.mojopkg
        - mojoproject.toml
        - test_*.mojo

about:
  homepage: https://github.com/thatstoasty/mist
  license: MIT
  license_file: LICENSE
  summary: mist lets you safely use advanced styling options on the terminal. https://github.com/thatstoasty/mist
  repository: https://github.com/thatstoasty/mist
